version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
  consul:
    image: consul
    ports:
      - 8500:8500
  mnsamples:
    image: ajiniesta/mn-samples
    links:
      - mongodb
      - consul
    environment:
      MICRONAUT_SERVER_HOST: mnsamples
#      MICRONAUT_SERVER_PORT: 8080
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
    ports:
      - 8080:8080