micronaut:
  server:
    port: -1
  application:
    name: mn-samples
consul:
  client:
    defaultZone: ${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}
mongodb:
  uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}
messages:
  database:
    name: messages
samples:
  api:
    version: v1