apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: mnsamples
  name: mnsamples
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mnsamples
    spec:
      containers:
      - env:
        - name: CONSUL_HOST
          value: consul
        - name: CONSUL_PORT
          value: "8500"
        - name: MICRONAUT_SERVER_HOST
          value: mnsamples
        - name: MONGO_HOST
          value: mongodb
        - name: MONGO_PORT
          value: "27017"
        image: ajiniesta/mn-samples
        name: mnsamples
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
